databases:
  - name: recipegroup
    databaseName: recipegroup
    user: recipegroup

services:
  - type: web
    name: recipegroup
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipegroup
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false